"""add text selection fields to comments

Revision ID: 804216b412de
Revises: b3886618479c
Create Date: 2025-12-04 01:36:03.132664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804216b412de'
down_revision = 'b3886618479c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('selected_text', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('selection_start', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('selection_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'selection_end')
    op.drop_column('comments', 'selection_start')
    op.drop_column('comments', 'selected_text')
    # ### end Alembic commands ###
