"""Add full_text column to patent_drafts

Revision ID: b3886618479c
Revises: 3678a1f70779
Create Date: 2025-12-04 01:11:25.467668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3886618479c'
down_revision = '3678a1f70779'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patent_drafts', sa.Column('full_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patent_drafts', 'full_text')
    # ### end Alembic commands ###
