"""Initial migration

Revision ID: 4a1f8d35ed63
Revises: 
Create Date: 2025-12-03 00:30:38.605052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1f8d35ed63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('INVENTOR', 'LAWYER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'AI_PROCESSING', 'READY_FOR_REVIEW', 'IN_REVIEW', 'REVISION_REQUESTED', 'APPROVED', name='disclosurestatus'), nullable=False),
    sa.Column('inventor_id', sa.Integer(), nullable=False),
    sa.Column('assigned_lawyer_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_lawyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inventor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disclosures_id'), 'disclosures', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosures.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('disclosure_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_snapshot', sa.JSON(), nullable=False),
    sa.Column('edited_by', sa.Integer(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosures.id'], ),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disclosure_versions_id'), 'disclosure_versions', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('DRAWING', 'DOCUMENT', 'IMAGE', name='filetype'), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_extension', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('s3_bucket', sa.String(), nullable=False),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('patent_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=False),
    sa.Column('ai_processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='aiprocessingstatus'), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('figure_index', sa.JSON(), nullable=False),
    sa.Column('ai_model_used', sa.String(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disclosure_id')
    )
    op.create_index(op.f('ix_patent_drafts_id'), 'patent_drafts', ['id'], unique=False)
    op.create_table('video_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_sessions_id'), 'video_sessions', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DISCLOSURE_CREATED', 'DISCLOSURE_UPDATED', 'DISCLOSURE_STATUS_CHANGED', 'COMMENT_ADDED', 'COMMENT_REPLY', 'LAWYER_ASSIGNED', 'DRAFT_READY', 'REVISION_REQUESTED', 'APPROVED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_video_sessions_id'), table_name='video_sessions')
    op.drop_table('video_sessions')
    op.drop_index(op.f('ix_patent_drafts_id'), table_name='patent_drafts')
    op.drop_table('patent_drafts')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_disclosure_versions_id'), table_name='disclosure_versions')
    op.drop_table('disclosure_versions')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_disclosures_id'), table_name='disclosures')
    op.drop_table('disclosures')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
